"""
paper_fig_legends.py — standalone, paste-INSIDE-the-tikzpicture legend
snippets for the three figures whose fig-level legend (fig.legend()) is
silently dropped by matplot2tikz (it only walks per-axes legends, not
fig.legends, so the .tex export never gets it even though the PNG/PDF do):
evolution RMSE grid, evolution M_phi grid, and the variants Pareto front.

Each output uses ONLY core TikZ path primitives (\\path/\\draw/\\node with
raw coordinates) — no \\begin{tabular}, \\begin{center}, bare \\\\, or
\\usetikzlibrary calls in the body. Those are text/paragraph-mode constructs
and are NOT valid as top-level content of a tikzpicture (only path/node
commands are), which is what breaks compilation when pasted directly inside
the figure's existing \\begin{tikzpicture}...\\end{tikzpicture}. No extra
tikz libraries are required (markers are drawn with plain \\path triangles/
rectangles/circles, matching how matplot2tikz itself draws pgfplots markers
in these files).

Each snippet is meant to be pasted verbatim right before the figure's own
\\end{tikzpicture} (i.e. after the existing suptitle \\draw(...) node[...]{...}
line), so it stacks below the plot grid via `current bounding box.south`.

Colors/markers are pulled directly from paper_fig_common's VARIANT_ORDER /
variant_color / variant_marker so the legend can't drift out of sync with
the actual plots.

Run from the project root:
    python main/analysis/paper_fig_legends.py
"""
import os
import re
import sys

_ROOT = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
if _ROOT not in sys.path:
    sys.path.insert(0, _ROOT)

from paper_fig_common import VARIANT_ORDER, variant_color, variant_marker
from paper_fig_pareto_baselines import SLIM_COLOR, ROLE_MARKERS, ROLE_LABELS, BASELINE_STYLES, BASELINE_KEYS

OUT_DIR = os.path.join(_ROOT, 'main', 'paper_figures')

LEGEND_BEGIN = '% >>> AUTO-LEGEND (generated by main/analysis/paper_fig_legends.py) >>>'
LEGEND_END = '% <<< AUTO-LEGEND <<<'

N_COLS = 4           # 16 variants -> 4 rows of 4 (fewer, wider columns for \LARGE text)
COL_WIDTH = 6.4      # cm, wide enough for "SLIM+NORMFIX" at \LARGE plus a roomy gap
ROW_HEIGHT = 1.15    # cm, generous vertical spacing at \LARGE line-height
HEADER_DROP = 1.05   # cm, header text -> first row
BLOCK_GAP = 0.85      # cm, gap between stacked blocks

LABEL_FONT = r'\LARGE'
HEADER_FONT = r'\LARGE\bfseries'


def _safe_name(algo: str) -> str:
    """'SLIM+2SIG' -> 'legSLIMp2SIG', 'SLIM*NORM12' -> 'legSLIMmNORM12' (valid TikZ color id)."""
    body = re.sub(r'[^A-Za-z0-9]', '', algo.replace('+', 'p').replace('*', 'm'))
    return f'leg{body}'


def _color_defs():
    return [f'\\definecolor{{{_safe_name(a)}}}{{HTML}}{{{variant_color(a).lstrip("#").upper()}}}'
            for a in VARIANT_ORDER]


def _hex_name(tag: str) -> str:
    """Deterministic, valid TikZ color identifier for an arbitrary tag (baseline/role name)."""
    return 'legHex' + re.sub(r'[^A-Za-z0-9]', '', tag)


def _hex_def(tag: str, hexcode: str) -> str:
    return f'\\definecolor{{{_hex_name(tag)}}}{{HTML}}{{{hexcode.lstrip("#").upper()}}}'


def _line_entry(color, dotted=False):
    style = ',densely dotted' if dotted else ''

    def draw(x, y):
        return [f'\\draw[color={color}, line width=2.2pt{style}] ({x:.3f},{y:.3f}) -- ({x+1.05:.3f},{y:.3f});']
    return draw, 1.05


def _marker_entry(color, marker):
    """marker: matplotlib-style code -- '^' triangle, 's' square, 'o' circle,
    'D' diamond, 'P' filled plus, 'X' filled cross. Covers every marker used
    across the variants and baselines Pareto figures."""
    def draw(x, y):
        cx = x + 0.20
        if marker == '^':
            return [f'\\path[draw={color}, fill={color}] '
                     f'({cx:.3f},{y+0.19:.3f}) -- ({cx-0.17:.3f},{y-0.14:.3f}) -- '
                     f'({cx+0.17:.3f},{y-0.14:.3f}) -- cycle;']
        if marker == 's':
            return [f'\\path[draw={color}, fill={color}] '
                     f'({cx-0.14:.3f},{y-0.14:.3f}) rectangle ({cx+0.14:.3f},{y+0.14:.3f});']
        if marker == 'o':
            return [f'\\path[draw={color}, fill={color}] ({cx:.3f},{y:.3f}) circle (0.16);']
        if marker == 'D':
            return [f'\\path[draw={color}, fill={color}] '
                     f'({cx:.3f},{y+0.18:.3f}) -- ({cx+0.14:.3f},{y:.3f}) -- '
                     f'({cx:.3f},{y-0.18:.3f}) -- ({cx-0.14:.3f},{y:.3f}) -- cycle;']
        if marker == 'P':
            return [f'\\path[draw=none, fill={color}] '
                     f'({cx-0.17:.3f},{y-0.06:.3f}) rectangle ({cx+0.17:.3f},{y+0.06:.3f});',
                     f'\\path[draw=none, fill={color}] '
                     f'({cx-0.06:.3f},{y-0.17:.3f}) rectangle ({cx+0.06:.3f},{y+0.17:.3f});']
        if marker == 'X':
            return [f'\\draw[color={color}, line width=3.2pt] '
                     f'({cx-0.15:.3f},{y-0.15:.3f}) -- ({cx+0.15:.3f},{y+0.15:.3f});',
                     f'\\draw[color={color}, line width=3.2pt] '
                     f'({cx-0.15:.3f},{y+0.15:.3f}) -- ({cx+0.15:.3f},{y-0.15:.3f});']
        raise ValueError(f'unsupported marker {marker!r}')
    return draw, 0.40


def _circle_entry(color, filled):
    fill = color if filled else 'none'

    def draw(x, y):
        cx = x + 0.20
        return [f'\\path[draw={color}, fill={fill}] ({cx:.3f},{y:.3f}) circle (0.16);']
    return draw, 0.40


def _block(entries, n_cols, header, row_height=ROW_HEIGHT, col_width=COL_WIDTH):
    """entries: list of ((draw_fn, swatch_w), label). Returns list of tikz command lines
    for one self-contained legend block, local origin (0,0) = top-left."""
    lines = []
    if header:
        lines.append(f'\\node[anchor=west, font={HEADER_FONT}, text=black] '
                      f'at (0,0) {{{header}}};')
    n_rows = (len(entries) + n_cols - 1) // n_cols
    for i, ((draw_fn, swatch_w), label) in enumerate(entries):
        r, c = divmod(i, n_cols)
        x0 = c * col_width
        y0 = -HEADER_DROP - r * row_height
        lines.extend(draw_fn(x0, y0))
        lines.append(f'\\node[anchor=west, font={LABEL_FONT}, text=black] '
                      f'at ({x0+swatch_w+0.35:.3f},{y0:.3f}) {{{label}}};')
    total_w = n_cols * col_width
    total_h = HEADER_DROP + n_rows * row_height
    return lines, total_w, total_h


def _stack_blocks(blocks):
    """blocks: list of (lines, width, height). Wrap each in a scope shifted below
    the running current-bounding-box, centered on its own width."""
    out = []
    for lines, width, _height in blocks:
        out.append(f'\\begin{{scope}}[shift={{(current bounding box.south)}}, '
                    f'yshift=-{BLOCK_GAP:.2f}cm, xshift=-{width/2:.3f}cm]')
        out.extend('  ' + ln for ln in lines)
        out.append('\\end{scope}')
    return '\n'.join(out)


def build_evolution_rmse_legend():
    variant_entries = [(_line_entry(_safe_name(a)), a) for a in VARIANT_ORDER]
    style_entries = [
        (_line_entry('black', dotted=False), 'Train'),
        (_line_entry('black', dotted=True), 'Test'),
    ]
    block1 = _block(variant_entries, N_COLS, 'Variant (color)')
    block2 = _block(style_entries, 2, 'Line style', col_width=4.5)
    header = (
        '% Legend for evolution_rmse_grid.tex -- matplot2tikz drops fig.legend()\n'
        '% (it only walks per-axes legends, not fig-level ones), so this rebuilds it\n'
        '% with plain TikZ \\path/\\draw/\\node commands -- no tabular/center/\\\\ and no\n'
        '% \\usetikzlibrary calls, so it is valid pasted directly INSIDE a tikzpicture.\n'
        '% No extra libraries needed. Paste this block right before the figure\'s own\n'
        '% \\end{tikzpicture} (i.e. after its existing suptitle \\draw(...) node{...} line).\n\n'
    )
    return header + '\n'.join(_color_defs()) + '\n\n' + _stack_blocks([block1, block2]) + '\n'


def build_evolution_mphi_legend():
    variant_entries = [(_line_entry(_safe_name(a)), a) for a in VARIANT_ORDER]
    block1 = _block(variant_entries, N_COLS, 'Variant (color)')
    header = (
        '% Legend for evolution_mphi_grid.tex -- matplot2tikz drops fig.legend()\n'
        '% (it only walks per-axes legends, not fig-level ones), so this rebuilds it\n'
        '% with plain TikZ \\path/\\draw/\\node commands -- no tabular/center/\\\\ and no\n'
        '% \\usetikzlibrary calls, so it is valid pasted directly INSIDE a tikzpicture.\n'
        '% No extra libraries needed. Paste this block right before the figure\'s own\n'
        '% \\end{tikzpicture} (i.e. after its existing suptitle \\draw(...) node{...} line).\n\n'
    )
    return header + '\n'.join(_color_defs()) + '\n\n' + _stack_blocks([block1]) + '\n'


def build_pareto_variants_legend():
    variant_entries = [(_marker_entry(_safe_name(a), variant_marker(a)), a) for a in VARIANT_ORDER]
    key_entries = [
        (_marker_entry('gray', '^'), 'SLIM+ (sum)'),
        (_marker_entry('gray', 's'), 'SLIM* (mul)'),
        (_circle_entry('gray', True), 'Filled = Pareto-optimal'),
        (_circle_entry('gray', False), 'Hollow = dominated'),
    ]
    block1 = _block(variant_entries, N_COLS, 'Variant (color + shape)')
    block2 = _block(key_entries, 2, 'Shape / fill key', col_width=9.0)
    header = (
        '% Legend for pareto_variants.tex -- matplot2tikz drops fig.legend()\n'
        '% (it only walks per-axes legends, not fig-level ones), so this rebuilds it\n'
        '% with plain TikZ \\path/\\draw/\\node commands -- no tabular/center/\\\\ and no\n'
        '% \\usetikzlibrary calls (markers are hand-drawn triangles/squares/circles\n'
        '% via \\path, same technique matplot2tikz itself uses for pgfplots markers\n'
        '% in this file), so it is valid pasted directly INSIDE a tikzpicture. No\n'
        '% extra libraries needed. Paste this block right before the figure\'s own\n'
        '% \\end{tikzpicture} (i.e. after its existing suptitle \\draw(...) node{...} line).\n\n'
    )
    return header + '\n'.join(_color_defs()) + '\n\n' + _stack_blocks([block1, block2]) + '\n'


def build_pareto_baselines_legend():
    color_defs = [_hex_def('SLIMROLE', SLIM_COLOR)]
    color_defs += [_hex_def(a, BASELINE_STYLES[a]['color']) for a in BASELINE_KEYS]

    role_entries = [(_marker_entry(_hex_name('SLIMROLE'), ROLE_MARKERS[r]), f'SLIM -- {ROLE_LABELS[r]}')
                     for r in ROLE_MARKERS]
    baseline_entries = [(_marker_entry(_hex_name(a), BASELINE_STYLES[a]['marker']), a)
                         for a in BASELINE_KEYS]
    key_entries = [
        (_circle_entry('gray', True), 'Filled = Pareto-optimal'),
        (_circle_entry('gray', False), 'Hollow = dominated'),
    ]
    block1 = _block(role_entries + baseline_entries, 3, 'SLIM roles / baselines (color + shape)',
                     col_width=7.2)
    block2 = _block(key_entries, 2, 'Fill key', col_width=9.0)
    header = (
        '% Legend for pareto_baselines.tex -- matplot2tikz drops fig.legend()\n'
        '% (it only walks per-axes legends, not fig-level ones), so this rebuilds it\n'
        '% with plain TikZ \\path/\\draw/\\node commands -- no tabular/center/\\\\ and no\n'
        '% \\usetikzlibrary calls (markers are hand-drawn shapes via \\path, same\n'
        '% technique matplot2tikz itself uses for pgfplots markers in this file), so\n'
        '% it is valid pasted directly INSIDE a tikzpicture. No extra libraries needed.\n'
        '% Paste this block right before the figure\'s own \\end{tikzpicture} (i.e.\n'
        '% after its existing suptitle \\draw(...) node{...} line).\n\n'
    )
    return header + '\n'.join(color_defs) + '\n\n' + _stack_blocks([block1, block2]) + '\n'


def embed_legend_in_figure(figure_path, legend_body):
    """Splice legend_body directly into figure_path, right before its final
    \\end{tikzpicture}. Idempotent: re-running replaces a previously embedded
    block (delimited by LEGEND_BEGIN/LEGEND_END) instead of duplicating it."""
    with open(figure_path, 'r', encoding='utf-8') as f:
        content = f.read()

    block = f'\n{LEGEND_BEGIN}\n{legend_body}\n{LEGEND_END}\n'

    begin_idx = content.find(LEGEND_BEGIN)
    if begin_idx != -1:
        end_idx = content.find(LEGEND_END, begin_idx) + len(LEGEND_END)
        content = content[:begin_idx].rstrip('\n') + block + content[end_idx:].lstrip('\n')
    else:
        marker = '\\end{tikzpicture}'
        last = content.rfind(marker)
        if last == -1:
            raise ValueError(f'{figure_path}: no \\end{{tikzpicture}} found to splice legend before')
        content = content[:last] + block + content[last:]

    with open(figure_path, 'w', encoding='utf-8') as f:
        f.write(content)
    print(f'  Embedded legend -> {figure_path}')


if __name__ == '__main__':
    os.makedirs(OUT_DIR, exist_ok=True)

    figures = {
        'evolution_rmse_grid.tex': build_evolution_rmse_legend(),
        'evolution_mphi_grid.tex': build_evolution_mphi_legend(),
        'pareto_variants.tex': build_pareto_variants_legend(),
        'pareto_baselines.tex': build_pareto_baselines_legend(),
    }
    standalone = {
        'legend_evolution_rmse.tex': figures['evolution_rmse_grid.tex'],
        'legend_evolution_mphi.tex': figures['evolution_mphi_grid.tex'],
        'legend_pareto_variants.tex': figures['pareto_variants.tex'],
        'legend_pareto_baselines.tex': figures['pareto_baselines.tex'],
    }
    for fname, content in standalone.items():
        path = os.path.join(OUT_DIR, fname)
        with open(path, 'w', encoding='utf-8') as f:
            f.write(content)
        print(f'  Saved -> {path}')

    for fname, legend_body in figures.items():
        embed_legend_in_figure(os.path.join(OUT_DIR, fname), legend_body)
